In [4]:
import numpy as np
from scipy import stats, integrate, optimize
from scipy.linalg import lu

# Ví dụ 1: Các hàm thống kê
mean = np.mean(data)
std_dev = np.std(data)
kurtosis = stats.kurtosis(data)
skewness = stats.skew(data)

print(f"Mean: {mean}, Standard Deviation: {std_dev}")
print(f"Kurtosis: {kurtosis}, Skewness: {skewness}")

# Ví dụ 2: Tích phân
result, error = integrate.quad(lambda x: np.exp(-x**2), -np.inf, np.inf)
print(f"Integral result: {result}, Error: {error}")

# Ví dụ 3: Tối ưu hóa
def func(x):
    return x**2 + 10*np.sin(x)

result = optimize.minimize(func, x0=0)
print(f"Optimization result: {result.x}")

# Ví dụ 4: Đại số tuyến tính
P, L, U = lu(A)
print("P matrix:\n", P)
print("L matrix:\n", L)
print("U matrix:\n", U)


Mean: -0.00553837397874423, Standard Deviation: 0.9696717678059357
Kurtosis: -0.23857871325596713, Skewness: -0.09132297537018762
Integral result: 1.7724538509055159, Error: 1.4202637059452923e-08
Optimization result: [-1.30644012]
P matrix:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L matrix:
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
U matrix:
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
