# NumPy Basics

NumPy is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures.

## Importing NumPy

First, we need to import NumPy. It is usually imported under the alias `np`.

In [8]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

## Creating Arrays

NumPy arrays are the main way to store and manipulate data. We can create arrays from Python lists or using NumPy functions.

In [2]:
# Creating a 1D array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D array from a list of lists
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

NameError: name 'np' is not defined

## Basic Operations

NumPy supports many basic operations like addition, subtraction, multiplication, and division.

In [3]:
# Element-wise addition
print(arr1 + arr1)

# Element-wise subtraction
print(arr1 - arr1)

# Element-wise multiplication
print(arr1 * arr1)

# Element-wise division
print(arr1 / arr1)

[2 4 6 8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]


## Advanced Operations

NumPy also supports more advanced operations like broadcasting, slicing, and indexing.

In [4]:
# Broadcasting example
print(arr2 * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
# Slicing example
print(arr1[1:3])
print(arr2[1:, :2])

[2 3]
[[4 5]
 [7 8]]
