# NumPy Operators

NumPy offers a wide range of operators for performing operations on arrays. This notebook provides examples of basic arithmetic, comparison, and logical operations using NumPy.

## Importing NumPy

First, we need to import NumPy. It is usually imported under the alias `np`.

In [1]:
import numpy as np

## Basic Arithmetic Operations

NumPy supports element-wise arithmetic operations such as addition, subtraction, multiplication, and division.

In [2]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Element-wise addition
print(arr + arr)

# Element-wise subtraction
print(arr - arr)

# Element-wise multiplication
print(arr * arr)

# Element-wise division
print(arr / arr)

[2 4 6 8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 2. 3. 4. 5.]


## Comparison Operations

NumPy supports element-wise comparison operations such as greater than, less than, and equal to.

In [3]:
# Element-wise comparison
print(arr > 2)
print(arr == 5)
print(arr <= 5)

[ True  True False False False]
[False False False False  True]
[ True  True  True  True  True]


## Logical Operations

NumPy supports element-wise logical operations such as logical and, logical or, and logical not.

In [4]:
# Element-wise logical operations
print(np.logical_and(arr > 2, arr < 4))
print(np.logical_or(arr < 3, arr > 4))
print(np.logical_not(arr < 3))

[False  True False False False]
[ True  True  True  True False]
[False False  True  True  True]
