In [1]:
import torch

# Tạo một tensor 1D (vector)
tensor_1d = torch.tensor([1, 2, 3, 4])

# Tạo một tensor 2D (ma trận)
tensor_2d = torch.tensor([[1, 2], [3, 4]])

# Thực hiện phép toán giữa các tensor
result = tensor_1d + 2  # Thêm 2 vào từng phần tử trong tensor_1d
print(tensor_1d)
print(tensor_2d)
print(result)

tensor([1, 2, 3, 4])
tensor([[1, 2],
        [3, 4]])
tensor([3, 4, 5, 6])
