## Kiểu dữ liệu của tensor

In [3]:
import torch

# Tạo một tensor có kiểu dữ liệu số nguyên
tensor_int = torch.tensor([1, 2, 3, 4, 5])
print("Tensor int:")
print(tensor_int)
print("Type:", type(tensor_int))
print("dtype:", tensor_int.dtype)

# Thay đổi loại dữ liệu của tensor thành số thực
tensor_float = tensor_int.float()
print("\nTensor float:")
print(tensor_float)
print("Type:", type(tensor_float))
print("dtype:", tensor_float.dtype)

# Tạo một tensor có kiểu dữ liệu phức
tensor_complex = torch.tensor([1, 2, 3], dtype=torch.complex64)
print("\nTensor complex:")
print(tensor_complex)
print("Type:", type(tensor_complex))
print("dtype:", tensor_complex.dtype)

Tensor int:
tensor([1, 2, 3, 4, 5])
Type: <class 'torch.Tensor'>
dtype: torch.int64

Tensor float:
tensor([1., 2., 3., 4., 5.])
Type: <class 'torch.Tensor'>
dtype: torch.float32

Tensor complex:
tensor([1.+0.j, 2.+0.j, 3.+0.j])
Type: <class 'torch.Tensor'>
dtype: torch.complex64
