## Matrix

In [18]:
import torch

# Tạo một ma trận 2 chiều (6x1) chứa các giá trị số nguyên
X = torch.tensor([
    [10],
    [30],
    [40],
    [50],
    [80],
    [90]
])

# In ra ma trận X
print("Ma trận X:")
print(X)

# In ra phần tử đầu tiên của ma trận X (giá trị trong hàng đầu, cột đầu tiên)
print("\nPhần tử đầu tiên của ma trận X:")
print(X[0])

# In ra tất cả các phần tử trong hàng đầu của ma trận X (cột đầu tiên)
print("\nTất cả các phần tử trong hàng đầu của ma trận X:")
print(X[0, :])  # : là ký hiệu chỉ định toàn bộ cột

# In ra số lượng cột trong ma trận X
print("\nSố lượng cột trong ma trận X:")
print(X.size(1))  # size() là hàm trả về kích thước của ma trận, ở đây chúng ta muốn lấy kích thước thứ 2 (số cột)

# In ra tất cả các phần tử trong cột đầu tiên của ma trận X
print("\nTất cả các phần tử trong cột đầu tiên của ma trận X:")
print(X[:, 0])  # : là ký hiệu chỉ định toàn bộ hàng

# Tạo một ma trận mới Y bằng cách sử dụng công thức phép nhân số hạng của X
Y = torch.tensor([
    [10, 20],
    [30, 40]
])

# In ra ma trận Y
print("\nMa trận Y:")
print(Y)

# Tạo một ma trận mới Z bằng cách thêm 10 vào mỗi phần tử của ma trận X
Z = X + 10

# In ra ma trận Z
print("\nMa trận Z (ma trận X cộng với 10):")
print(Z)

# Tạo một ma trận mới X_float có kiểu dữ liệu số thực từ ma trận X
X_float = torch.tensor([
    [10.0],
    [30.0],
    [40.0],
    [50.0],
    [80.0],
    [90.0]
])

# In ra ma trận X_float
print("\nMa trận X_float:")
print(X_float)

# Tính toán tổng của tất cả các phần tử trong ma trận X_float
total_X = torch.sum(X_float)
print("\nTổng của tất cả các phần tử trong ma trận X_float:")
print(total_X)

# Tính toán trung bình của tất cả các phần tử trong ma trận X_float
mean_X = torch.mean(X_float)
print("\nTrung bình của tất cả các phần tử trong ma trận X_float:")
print(mean_X)

Ma trận X:
tensor([[10],
        [30],
        [40],
        [50],
        [80],
        [90]])

Phần tử đầu tiên của ma trận X:
tensor([10])

Tất cả các phần tử trong hàng đầu của ma trận X:
tensor([10])

Số lượng cột trong ma trận X:
1

Tất cả các phần tử trong cột đầu tiên của ma trận X:
tensor([10, 30, 40, 50, 80, 90])

Ma trận Y:
tensor([[10, 20],
        [30, 40]])

Ma trận Z (ma trận X cộng với 10):
tensor([[ 20],
        [ 40],
        [ 50],
        [ 60],
        [ 90],
        [100]])

Ma trận X_float:
tensor([[10.],
        [30.],
        [40.],
        [50.],
        [80.],
        [90.]])

Tổng của tất cả các phần tử trong ma trận X_float:
tensor(300.)

Trung bình của tất cả các phần tử trong ma trận X_float:
tensor(50.)
